[build]
  command = ""
  publish = "client"

# Proxy frontend /api/* calls to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://zevvy-main-site.onrender.com/api/:splat"
  status = 200
  force = true
  to = "https://zevvy-main-site.onrender.com/api/:splat"
